apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: services
  namespace: argo-cd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'argo-cd'
      server: '*'
  sourceRepos:
    -  https://github.com/rowi1de/argocd
