apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: services
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'services'
      server: '*'
  sourceRepos:
    -  https://github.com/rowi1de/argocd
    -  ghcr.io/rowi1de/graphql-reactive # OCI
    -  ghcr.io/rowi1de/k8s-local-storage # OCI
    -  https://rowi1de.github.io/graphql-reactive/k8s/helm # GitHub Pages / Chart Releaser
