apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-hub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade on delete
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: traefik-hub
  source:
    repoURL: 'https://helm.traefik.io/hub'
    chart: hub-agent
    targetRevision:  1.0.0
    helm:
      values: |
        token: "https://github.com/traefik/hub-helm-chart/issues/64"
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true