apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade on delete
spec:
  project: vault
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault
    # https://github.com/hashicorp/vault-helm/blob/main/Chart.yaml
    targetRevision: v0.16.0
    helm:
      values: |
        ui:
          enabled: true
          service:
            serviceType: ClusterIP
        server:
          extraEnvironmentVars:
            VAULT_API_ADDR: "http://$(HOSTNAME).vault-internal:8200"
          ha:
            enabled: true
            raft:
              enabled: true
              config: |
               ui = true
               disable_mlock = true
               cluster_addr = "https://HOSTNAME.vault-internal:8201"
               service_registration "kubernetes" {}

               listener "tcp" {
                 tls_disable = 1
                 proxy_protocol_behavior = "use_always"
                 address = "[::]:8200"
                 cluster_address = "[::]:8201"
               }
               storage "raft" {
                 path = "/vault/data"

                 retry_join {
                   leader_api_addr = "http://vault-0.vault-internal:8200"
                 }
                 retry_join {
                   leader_api_addr = "http://vault-1.vault-internal:8200"
                 }
                 retry_join {
                   leader_api_addr = "http://vault-2.vault-internal:8200"
                 }
               }

          dataStorage:
            size: 10Gi
            storageClass: csi-disk
            annotations:
               everest.io/disk-volume-type: SSD


  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true