apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-root
  namespace: traefik
spec:
  redirectRegex:
    regex: (.*)
    replacement: https://github.com/rowi1de
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: traefik
spec:
  basicAuth:
    secret: traefik-basic-auth
