apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphql-reactive
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade on delete
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  source:
    repoURL: ghcr.io/rowi1de/graphql-reactive
    # https://argo-cd.readthedocs.io/en/stable/user-guide/tracking_strategies/
    targetRevision: *
    chart: graphql-reactive
  project: services
  destination:
    server: https://kubernetes.default.svc
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
