apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    repoURL:  https://github.com/rowi1de/argocd
    targetRevision:  HEAD
    path: rabbitmq/rabbitmq-cluster
    helm:
      releaseName: rabbitmq-cluster
  project: rabbitmq
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
