apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonar
spec:
  destination:
    namespace: sonarqube
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://charts.bitnami.com/bitnami # https://artifacthub.io/packages/helm/bitnami/sonarqube
    targetRevision: "1.0.13"
    chart: sonarqube
    helm:
      releaseName: sonarqube
      values: |
        sonarqubeUsername: admin
        sonarqubePassword: admin
        replicaCount: 1
        resources:
          requests:
            cpu: 50m
            memory: 1Gi
        service:
          type: ClusterIP
        ingress:
          enabled: false
          hostname: sonarqube.robert-wiesner.de
          apiVersion: extensions/v1beta1
        postgresql:
          auth:
            username: sonarqube
            password: sonarqube
            database: sonarqube

  project: infrastructure
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
