apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: hello@robert-wiesner.de
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01: #only works for non-wildcard
          ingress:
            class: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hello@robert-wiesner.de
    privateKeySecretRef:
      name: letsencrypt-stage
    solvers:
      # https://cert-manager.io/docs/configuration/acme/dns01/google needed for wildcard
      - dns01:
          cloudDNS:
            # The ID of the GCP project
            project: gke-free-k8
            # This is the secret used to access the service account
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: robert-wiesner.de
  namespace: cert-manager
spec:
  secretName: robert-wiesner.de
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.robert-wiesner.de'
  dnsNames:
    - robert-wiesner.de
    - '*.robert-wiesner.de'
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik,services,argocd"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "traefik,services,argocd"