apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade on delete
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: cert-manager
  source:
    repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision:  v1.8.0
    helm:
      values: |
        installCRDs: true
        podDnsPolicy: None
        podDnsConfig:
          nameservers:
            - 8.8.8.8
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true