apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argo-cd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/rowi1de/argocd
    targetRevision:  HEAD
    directory:
      recurse: true
    path: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true