apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: argocd
spec:
  project: services
  source:
    repoURL: https://github.com/rowi1de/argocd
    targetRevision:  HEAD
    directory:
      recurse: true
    path: services
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true