#!/bin/sh

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# cd to project root
cd "$SCRIPT_DIR/.." || exit

RED="\033[0;31m"
GREEN="\033[0;32m"
NC="\033[0m" # No Color


ymlChanges=$(git diff --diff-filter=ACM --cached --name-only | grep "k8s.*\.yml" | tr '\n' ' ')
if [ -n "$ymlChanges" ]; then
    printf "Please use *.yaml for %s" "$ymlChanges"
    exit 1
fi

# ignoring k8s directory because of helm, github actions
yamllint "**/*.yaml" --ignore="**/node_modules/**" --ignore="**/k8s/**"  --ignore="**/.github/workflows/**"

k8sChanges=$(git diff --diff-filter=ACM --cached --name-only | grep "k8s.*\.yaml" | tr '\n' ' ')
if [ -n "$k8sChanges" ]; then
    printf "k8s changes detected. Executing kube-linter...\n"
    kube-linter lint "$k8sChanges"
fi


helmChanges=$(ct list-changed --chart-dirs k8s)
if [ -n "$helmChanges" ] &&  false  ; then
    printf "Helm changes detected. Executing ct lint...\n"
    ct lint --chart-dirs k8s --all
    retVal=$?
    if [ $retVal -ne 0 ]; then
      exit $retVal
    fi
fi


scriptChanges=$(git diff --diff-filter=ACM --cached --name-only | grep ".*\.sh")
if [ -n "$scriptChanges" ]; then
    printf "Script changes detected. Executing shfmt...\n"
    echo "$scriptChanges" | while read -r file ; do
        echo "Processing $file"
        shfmt -w -i 4 "$file"
    done
fi
