name: Create Deployment PR
on: 
 repository_dispatch:
  

jobs:
  update-helm-release:
    runs-on: ubuntu-latest
    steps:
    
    - name: Get Latest Release
      id: latest-release
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        repository: ${{ github.event.client_payload.repository }}
        excludes:  pre-release
        
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Helm Upgrade OCI Image Tag
      uses: endaft/action-yamler@v1.0.9
      with:
         file: ./services/graphql-reactive.yaml
         path: spec.source.targetRevision 
         set:  ${{ steps.latest-release.outputs.release }}
         
    - id: create-pull-request-action
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.REPO_TOKEN }}
        branch: "deploy-${{ github.event.client_payload.repository }}-${{ steps.latest-release.outputs.release }}"
        base: main
        reviewers: ${{ github.event.client_payload.actor }}
        delete-branch: true
        title: "[DEPLOY] ${{ github.event.client_payload.repository }} ${{ steps.latest-release.outputs.release }} by ${{ github.event.client_payload.actor }}"
        labels: deploy
 
