name: Update Helm Version based on Release Trigger
on: 
 release:
 pull_request: 

jobs:
  update-helm-release:
    runs-on: ubuntu-latest
    steps:
    
    - name: Get Latest Release
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        owner: rowi1de
        # The repository name
        repo: graphql-reactive
        excludes:  pre-release
  
