name: Update Helm Version based on Release Trigger
on: 
 release:
 pull_request: 

jobs:
  update-helm-release:
    runs-on: ubuntu-latest
    steps:
    
    - name: Get Latest Release
      id: latest-release
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        owner: rowi1de
        # The repository name
        repo: graphql-reactive
        excludes:  pre-release
        
    - name: Checkout
      uses: actions/checkout@v
        
    - name: Helm Upgrade OCI Image Tag
      uses: endaft/action-yamler@v1.0.9
      with:
         file: ./services/graphql-reactive.yaml
         path: spec.targetRevision 
         set:  ${{ steps.latest-release.outputs.release }}
  
