name: Update Helm Version based on Release Trigger
on: 
 release:
 pull_request: 

jobs:
  update-helm-release:
    runs-on: ubuntu-latest
    steps:
    
    - name: Get Latest Release
      id: latest-release
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        owner: rowi1de
        # The repository name
        repo: graphql-reactive
        excludes:  pre-release
        
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Helm Upgrade OCI Image Tag
      uses: endaft/action-yamler@v1.0.9
      with:
         file: ./services/graphql-reactive.yaml
         path: spec.source.targetRevision 
         set:  ${{ steps.latest-release.outputs.release }}
         
    - id: create-pull-request-action
      name: Create Pull Request
      uses: quangvo09/create-pull-request-action@v1.0.1
      with:
        # GitHub token
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch_prefix: main
        # base branch for create pr
        base_branch: main
        # request reviewers
        reviewers: rowi1de

  
